### ISSUE TITLE
not work :(

### ISSUE THREAD

**Issue by cnutenor** [a-ws-m/multi-part-messages#1] opened 2021-09-02 22:32 UTC
HI, something not work. doble clic not work in foundry 0.89

**Comment by a-ws-m** [comment] 2021-09-04 13:59
Hi, thanks for raising this issue. I'll test with that version of Foundry when I next get a chance, but I'm going on holiday soon so it may be a short while before I can fix the issue. Please could you provide the [flavour text source code](https://github.com/a-ws-m/multi-part-messages/blob/master/img/mace-source.png) for the item?

**Comment by a-ws-m** [comment] 2022-01-07 22:13
I couldn't reproduce this bug in Foundry 0.8.9 I'm afraid. I'm going to close this issue until further details are provided.

**Closed as completed by a-ws-m** 2022-01-07 22:13 UTC
